name:                mf-hask
version:             0.1.0.0
github:              "jonathanlorimer/mf-hask"
license:             BSD3
author:              "Jonathan Lorimer"
maintainer:          "jonathan_lorimer@mac.com"
copyright:           "2019 Jonathan Lorimer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jonathanlorimer/mf-hask#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- megaparsec
- text
- relude
- QuickCheck
- semigroups

library:
  source-dirs: src
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wredundant-constraints

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

tests:
  mf-hask-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wredundant-constraints
    dependencies:
    - mf-hask
    - hspec
    - QuickCheck
    - hspec-discover
